#!/bin/bash

# our name
name=$(basename "$0")

# list of installed shells
shells='/etc/shells'

# we need shell list
if ! [ -f "$shells" ]; then
  echo "$name: $shells not a file"
  exit 1
fi

# generate bpftrace condition for each shell
#  remove first line from file
#  get basename of each shell path
#  sort and remove duplicates
#  generate bpftrace condition
cond="$(tail -n +2 "$shells" | xargs basename -a | sort -u | awk '
{
  printf("%scomm == \"%s\"", or, $0)
  or = " || "
}
')"
if [ $? -ne 0 ]; then
  echo "$name: could not generate condition"
  exit $?
fi

# print exec* arguments for any command run by any shell
sudo "$HOME/bpftrace/result/bin/bpftrace" -e "
BEGIN
{
  printf(\"%-20s %-20s ARGV\n\", \"PID\", \"SHELL\");
}
tracepoint:syscalls:sys_enter_exec*
/$cond/
{
  printf(\"%-20d %-20s \", pid, comm);
  join(args.argv);
}
"
